### ISSUE TITLE
Question: Why is both in one package?

### ISSUE THREAD

**Issue by ndberg** [DataHiveDevelopment/Laravel-Introspection#1]
Thanks for sharing your package.

Questions: Why didn't you split up the package in two packages, one for the auth server and one for the resource server? Is it necessary that the resource server has a dependency to laravel/passport?

I'm asking because I just started to build an own package to handle oauth for a separated resource server, working with a central laravel/passport oauth server. But if your package fits my need, I don't have to build it myself.

Thanks

**Comment by ReArmedHalo** [comment]
Hi @ndberg,

No reason honestly. I just didn't separate things. I'm hoping that I don't need this package for long and parts of what it provides gets integrated into Passport in a future release.

**Comment by ReArmedHalo** [comment]
I'll split things up when I can just to help keep things cleaner.

**Comment by ndberg** [comment]
For me it would feel cleaner to split it up.

**Comment by webfacer** [comment]
i also found it bit confusing, didn´t know exactly in the description what you mean with it until i read about it later. may be you shold it describe it better in the headline. that you will need to install it on both side (resource- and oauth-server).

**Comment by ReArmedHalo** [comment]
@webfacer you'll install this package on both sides currently. Sorry about the confusion. It still is on my todo list to split into an auth and resource server specific package.

**Comment by webfacer** [comment]
i mean it shoul take the confuison if you describe it just better in Read.me file. think for now it will do it.

**Comment by ReArmedHalo** [comment]
@webfacer does that help at all?

**Comment by webfacer** [comment]
awesome, nice thx by the way for fast responses, are you also on discord? would be awesome to chat there if some issues ocure, to optimize further documentation.

**Comment by ReArmedHalo** [comment]
@webfacer Yes, ReArmedHalo 8688

**Comment by webfacer** [comment]
did send you invite

**Comment by ReArmedHalo** [comment]
@webfacer @ndberg Development testing builds of the new packages are live! https://github.com/DataHiveDevelopment/passport-introspection-docs

Please give them a try and leave any feedback or suggestions you may have. I am doing some testing with a friend of mine to see how good the documentation is but I always welcome other feedback as well :)
