### ISSUE TITLE
Readme missing Trait

### ISSUE THREAD

**Issue by ndberg** [DataHiveDevelopment/Laravel-Introspection#2]
As far as I can see, this should be added to the documentation:

Add the Trait HasAccessToken to the User Model:
` use HasAccessToken;`

**Comment by ReArmedHalo** [comment]
Correct, that is part of the standard Passport installation. I can update the docs to point it out however. Thank you, I will update that tonight as well as put a place holder message in place for #1 warning of the decoupling.
