### ISSUE TITLE
[Deprecation] Composer notice on install

### ISSUE THREAD

**Issue by webfacer** [DataHiveDevelopment/Laravel-Introspection#3]
First thank god you provide this :)
Getting deprecation issue when installing it from Composer:
`Deprecation Notice: Class DataHiveDevelopment\Introspection\IntrospectionServiceProvider located in ./vendor/datahivedevelopment/laravel-introspection/src/IntrospectionClientServiceProvider.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

**Comment by ReArmedHalo** [comment]
Glad you are finding it useful!

Thanks for the heads up! I'll look into correcting this tonight and update the package.

**Comment by webfacer** [comment]
thanks for the fast response :)

**Comment by ReArmedHalo** [comment]
For my reference: https://github.com/composer/composer/releases/tag/1.10.0-RC
```
Deprecated: Added a warning when class names are being loaded by a PSR-4 or PSR-0 rule only due to classmap optimization, but would not otherwise be autoloadable. Composer 2.0 will stop autoloading these classes so make sure you fix your autoload configs.
```

**Comment by ReArmedHalo** [comment]
I lied, I think I fixed it, I don't have access to composer at the moment, can you test? I'm publishing a dev build now

**Comment by webfacer** [comment]
kk i will try, just a moment

**Comment by webfacer** [comment]
hmmm could it be that this tag have some error could not install it by tag nor by commit version getting every time an error

**Comment by ReArmedHalo** [comment]
It's very possible I screwed it up. I am pretty new to using composer as a package developer and not just a normal developer that uses composer :)

I was able to gain access to my dev system and successfully installed on a fresh Laravel 7 install using `composer require datahivedevelopment/laravel-introspection:dev-master` and I did not see the same error, I am going to republish as 2.1.0 release so then you should be able to install like normal.

**Comment by ReArmedHalo** [comment]
Published, give that a try:

`composer require datahivedevelopment/laravel-introspection`

Should give you 2.1.0

**Comment by webfacer** [comment]
yep now it is fine, oh oki id did it with dev-master but seems it could be on my side that i miss something, and thank you it worked well no Warnings from composer anymore

**Comment by ReArmedHalo** [comment]
Awesome! Let me know if you find any other issues or have any other requests.
