### ISSUE TITLE
Is it possible to configure to use HTTP instead of HTTPS? 

### ISSUE THREAD

**Issue by webfacer** [DataHiveDevelopment/Laravel-Introspection#4]
Is it possible to change header protocol?

**Comment by ReArmedHalo** [comment]
Sorry what are you asking for?

**Comment by webfacer** [comment]
the request url is build now with https but i need it for local just in http. could i change somehow, is there a option or configuration file where i can chage it?

**Comment by webfacer** [comment]
oh sorry its in the .env file i thought you build the url forgot the configuration file. my fault

**Comment by ReArmedHalo** [comment]
I don't believe I've hardcoded HTTPS anywhere in the package. Just modify the configuration values with http URLs and things should work fine.

I believe the following in your .env will suffice:
```
INTROSPECTION_TOKEN_URL=http://authserver.test/oauth/token
INTROSPECTION_ENDPOINT=http://authserver.test/introspect
```
