### ISSUE TITLE
Introspection creates a new token every time

### ISSUE THREAD

**Issue by ghost** [DataHiveDevelopment/Laravel-Introspection#6]
Hi,

I did not see this as part of the standard, however it appears that performing Introspection creates a new token for the resource server to use to access the introspection endpoint every time.

Is this a limitation to your implementation, or is this part of the standard? If not, how could we save the token for future use and only request a new one upon expiration, or use the refresh token?

**Comment by ReArmedHalo** [comment]
Limitation of my implementation. I could use the `Cache` helper probably to accomplish this. It doesn't make sense to use a database migration because more than likely we will only have the one token.

**Comment by ReArmedHalo** [comment]
I'm probably not going to "fix" this in the package's current state but rather will take care of it when I finish the separation of the server and client package. Things have been a bit slow so I'm hoping to accomplish that this coming weekend.

**Comment by ghost** [comment]
No problem, that sounds great, I look forward to implementing the two new packages. 

Also I want to thank you for it as it's perfect for an internal project I'm working on!

**Comment by ReArmedHalo** [comment]
Right so I didn't get it done that weekend, but I finally have gotten around to this. Server side has been re-written, not pushed live yet until I finish both parts and I am sure they work lol, but I did include using the cache for an access token.

Passport issues access tokens, by default, with a TTL of one year. I'm following that default but will allow it to be overridden. I am going to add a failsafe so if the cached token returns an error, we will attempt to fetch a fresh token anyways and try again before failing.

```php
    /**
     * Retrieve an OAuth access token from the cache, or fetch a new one from the authorization server.
     * TODO: Make use of the refresh_token?
     *
     * @return string
     * @throws RequestException
     */
    protected function getAccessToken()
    {
        // Get OAuth access token
        return Cache::remember('introspection.access_token', config('introspection.access_token_ttl', new DateInterval('P1Y')), function() {
            $response = Http::asForm()->get(config('introspection.token_url'), [
                'grant_type' => 'client_credentials',
                'client_id' => config('introspection.client_id'),
                'client_secret' => config('introspection.client_secret'),
                'scope' => config('introspection.token_scopes')
            ]);

            // If a client or server error occurs, throw a RequestException
            // Otherwise, return the access token
            return $response->throw()->json()['access_token'];
        });
    }
```

**Comment by ReArmedHalo** [comment]
@josephxanderson Development testing builds of the new packages are live! https://github.com/DataHiveDevelopment/passport-introspection-docs

I would appreciate any feedback and issues you may encounter. As I stated above I am now caching the token so a new one isn't requested every time.

I'm going to mark this as resolved now. Thank you!
